server:
 servlet:
   context-path: /osapi-oauth-server
 port: 13081

spring:
  profiles: default
  application:
    name: openslice-oauth-server
  datasource:
    url: jdbc:mysql://localhost/osdb?createDatabaseIfNotExist=true
    password: letmein0
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
    properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  cloud:
    consul:
      enabled: true
      host: http://localhost:8500
      port: 8500
      config:
        enabled: true
        prefix: config
        defaultContext: openslice
        data-key: osdata
        profileSeparator: '::'
        format: yaml        
      discovery:
        tags: openslice-microservice
        enabled: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        healthCheckInterval: 120s


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.apache.camel: INFO 
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
    
    
authclients:
  allowOrigins: 
  - "http://localhost:13000"
  clients:
    osapiWebClientId:
      clientId: "osapiWebClientId"
      tokenSecret: "secret"
      tokenExpirationsec: 3600
      scopes:
      - "openapi"
      - "admin"
      - "read"
      - "write"
      grantTypes:
      - "authorization_code"
      - "password"
      - "refresh_token"
      - "client_credentials"
      redirectUris:
      - "http://localhost:13000/osapi/webjars/springfox-swagger-ui/oauth2-redirect.html"
      - "http://localhost:13000/osapi/testweb/oauthresp.html"
    osapiWebClientIdOut:
      clientId: "osapiWebClientIdOut"
      tokenSecret: "secret"
      tokenExpirationsec: 3600
      allowOrigins: 
      - "http://localhost:13000"
      scopes:
      - "openapi"
      - "admin"
      - "read"
      - "write"
      grantTypes:
      - "authorization_code"
      - "password"
      - "refresh_token"
      - "client_credentials"
      redirectUris:
      - "http://localhost:13000/osapi/webjars/springfox-swagger-ui/oauth2-redirect.html"
      - "http://localhost:13000/osapi/testweb/oauthresp.html"

